---
- name: Deploy app to VPS
  hosts: vps
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: olyfaneva/back-end
        tag: latest
        source: pull

    - name: Stop old container if running
      docker_container:
        name: olyfaneva/back-end:latest
        state: stopped
      ignore_errors: yes

      

    - name: Run new container
      docker_container:
        name: back-end
        image: olyfaneva/back-end:latest
        state: started
        restart_policy: always
        published_ports:
          - published: 8005    # Port sur l'hôte
            target: 9000       # Port dans le conteneur
            protocol: tcp      # Protocole utilisé
