---
- name: Deploy app to VPS
  hosts: vps
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: olyfaneva/back-end
        tag: latest
        source: pull

    - name: Stop old container if running
      docker_container:
        name: back
        state: stopped
      ignore_errors: yes

    - name: Remove old container
      docker_container:
        name: back
        state: absent
      ignore_errors: yes

    - name: Run new container
      docker_container:
        name: back-end
        image: olyfaneva/back-end:latest
        state: started
        restart_policy: always
        published_ports:  # Correct key to map ports
          - "8000:8005"
