---
- name: Deploy app to VPS
  hosts: vps
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: olyfaneva/back-end
        tag: latest
        source: pull

    - name: Check if container is running
      command: docker ps --filter "name=back-end" --format "{{.Names}}"
      register: container_check
      changed_when: false

    - name: Stop old container if running
      docker_container:
        name: back-end
        state: stopped
      when: container_check.stdout.find('back-end') != -1

    - name: Remove old container
      docker_container:
        name: back-end
        state: absent
      ignore_errors: yes

    - name: Run new container
      docker_container:
        name: back-end
        image: olyfaneva/back-end:latest
        state: started
        restart_policy: always
        published_ports:
          - published: 8005
            target: 9000
            protocol: tcp
