version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: jenkins # Assurez-vous que Jenkins a les permissions nécessaires
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home # Persistance des données Jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Accès à Docker depuis Jenkins

volumes:
  jenkins_home:
